# Generated by Django 2.2 on 2020-10-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm_app', '0002_auto_20201013_0354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
