# Generated by Django 2.2 on 2020-11-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm_app', '0003_auto_20201022_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='movies',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
